### PR TITLE
Default box styling

### PR DESCRIPTION
**Pull request by Blackbaud-ToddRoberts**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-default-box-styling](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-default-box-styling)

**Comment by Blackbaud-ToddRoberts** [comment]
@Blackbaud-PaulCrowder should we handle default theme box like this, or just have box set the white bg and then backport elevation 0 & 1?

**Comment by Blackbaud-PaulCrowder** [comment]
> @Blackbaud-PaulCrowder should we handle default theme box like this, or just have box set the white bg and then backport elevation 0 & 1?

Default theme has no concept of elevation, correct? So every box would always have the same drop shadow? If that's the case, I'm fine with burning those styles into `.sky-box` for default theme and continuing to require elevation classes to be specified in modern. If we do want to carry over the concept of elevation to default theme, then I would suggest leaving them out and backporting all of the elevation classes from modern into default, even if higher elevations have the same drop shadow as lower elevations.

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-default-box-styling](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-default-box-styling)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-default-box-styling](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-default-box-styling)

**Review by Blackbaud-PaulCrowder — APPROVED** [review]

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-default-box-styling](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-default-box-styling)

**Pull request merged**
