### PR TITLE
Added modern styles for radio button and checkbox icons groups

### PR DESCRIPTION
**Pull request by Blackbaud-AlexKingman**
Design spec:
https://blackbaud.invisionapp.com/console/share/ESWIH1UGR2P/509645035

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-switch-modern-styles](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-switch-modern-styles)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-switch-modern-styles](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-switch-modern-styles)

**Review by johnhwhite — COMMENTED** [review]
Overall looks good, but the input focus ring has a border radius that doesn't seem to match the icon:

image

Should that match?

**Comment by Blackbaud-AlexKingman** [comment]
> Overall looks good, but the input focus ring has a border radius that doesn't seem to match the icon:
> 
> image
> 
> Should that match?

Good eye. That's actually pare of the pre-existing style. You can see it on the demo page: https://developer.blackbaud.com/skyux-forms/docs/radio?docs-active-tab=development

@Blackbaud-ToddRoberts Is this something we should fix?

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-switch-modern-styles](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-switch-modern-styles)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-switch-modern-styles](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-switch-modern-styles)

**Review by johnhwhite — DISMISSED** [review]
Code looks good.

**Review by Blackbaud-ToddRoberts — CHANGES_REQUESTED** [review]
Unselected state should have transparent bg

**Comment by Blackbaud-AlexKingman** [comment]
> Unselected state should have transparent bg

@Blackbaud-ToddRoberts Done.

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-switch-modern-styles](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-switch-modern-styles)

**Review by Blackbaud-ToddRoberts — APPROVED** [review]

**Review by johnhwhite — APPROVED** [review]

**Pull request merged**
