### PR TITLE
Status indicator > Add docs

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-add-docs](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-add-docs)

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-add-docs](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-add-docs)

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-add-docs](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-add-docs)

**Comment by Blackbaud-AdamFunderburk** [comment]
I don't have permission to push to skyux-theme, so can someone else please update the image assets for the Status indicator guidelines? The updated images are here https://blackbaudinc.box.com/s/cn8j9517i8uw2hs5pb961yqvetqmqdov

**Comment by blackbaud-johnly** [comment]
I'm looking into it @Blackbaud-AdamFunderburk. Not sure if I have rights either, but I'll test that by trying to update the pics.

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-add-docs](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-add-docs)

**Comment by Blackbaud-AdamFunderburk** [comment]
I think the "Demo" header is using the wrong class.
image

Everything else looks awesome.

**Comment by blackbaud-johnly** [comment]
The Demo header here looks the same to me as in popover:
image
Does that mean we need add that header to the issue I created for docs-tools as opposed to fixing the header in this PR?

**Comment by Blackbaud-SteveBrush** [comment]
The heading issue will be resolved in an upcoming release of `@skyux/docs-tools`. https://github.com/blackbaud/skyux-docs-tools/issues/16

**Pull request merged**
