### PR TITLE
Update SKY UX icons to 4.0.0-beta.2

### PR DESCRIPTION
**Pull request by Blackbaud-PaulCrowder**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-skyux-icons-update](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-skyux-icons-update)

**Review by Blackbaud-AlexKingman — DISMISSED** [review]

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-skyux-icons-update](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-skyux-icons-update)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-skyux-icons-update](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-skyux-icons-update)

**Review by Blackbaud-AlexKingman — DISMISSED** [review]

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-skyux-icons-update](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-skyux-icons-update)

**Review by Blackbaud-AlexKingman — APPROVED** [review]

**Pull request merged**
