### PR TITLE
Box docs page with demo and examples

### PR DESCRIPTION
**Pull request by Blackbaud-AlexKingman**
#155 

Add `?svcid=skyux-modern` to the URL to see box's modern theme applied.

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-box-docs](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-box-docs)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-box-docs](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-box-docs)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-box-docs](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-box-docs)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-box-docs](https://developer.blackbaud.com/skyux-theme?_sp.spa=pr-box-docs)

**Review by Blackbaud-SteveBrush — APPROVED** [review]

**Pull request merged**
